// This file is auto-generated by scripts/generate-link-map.mjs
// Do not edit manually.

export const generatedLinkMap: Record<string, string[]> = {
  "\\about": ["\\ai", "\\contact", "\\mathematics"],
  "\\ai": ["\\mathematics"],
  "\\contact": [],
  "\\elena": ["\\iceland", "\\mathematics"],
  "\\iceland": ["\\ai", "\\elena", "\\mathematics"],
  "\\mathematics": ["\\ai"],
  "\\unknown": ["\\about"],
};
